---
title: "ishares_import"
output: html_notebook
---

```{r initialize, message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
library(stringr)
```

Time to import ishares data, they are contained in the same excel sheet

lets get the tickers first

```{r}
ishares <- read_excel("data/raws/ishare_us.xlsx")
ishares
```

isolate them and convert to a mappable list structure

```{r}
names <- ishares %>% 
  select(Ticker) %>% 
  pull() 
  
names[1:6]
```


```{r}
etf_xls <- read_excel("data/ishares/AAXJ.xlsx", sheet = "Holdings", skip = 8)
etf_xls
```

create the function to extract holdings

```{r}
importholdingclean <- function(ticker) {
  #take the name and interp into full location
  location = str_glue('data/ishares/{ticker}.xlsx')
  print(str_c('Trying to import.....', ticker))
  
  xls <- read_excel(location, sheet = "Holdings", skip = 8)
  colnames(xls) <- str_replace_all(colnames(xls), " ", "_")
  return(xls)
}
```

```{r}
importholdingclean('AAXJ')
```

It works so now lets import all of the etfs

```{r}
ishare_holdings <- names %>% 
  map(~importholdingclean(.x))
```

now we will bind this to the ticker names to create a dataframe

```{r}
ishare_total_holdings <- ishares %>% 
  select(Ticker) %>%
  add_column(holdings = ishare_holdings)
```


```{r}
ishare_total_holdings <- ishare_total_holdings %>% 
  unnest(holdings) %>% 
  rename(ID = Ticker1)
```

write this out to a feather

```{r}
library(feather)
write_feather(ishare_total_holdings, "ishare_holdings.feather")
```


